/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HelloGradle;

import org.junit.Test;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
    	System.out.println("Library works");
//        Library classUnderTest = new Library("test library");
//        assertTrue("Science should be in library's selection", classUnderTest.isInSelection("Science"));
//        assertTrue("Children should be in library's selection", classUnderTest.isInSelection("Children"));
//        assertFalse("Drama should not be in library's selection", classUnderTest.isInSelection("Drama"));
    }
}
